### ISSUE TITLE
a4paper setting causes overlapping words

### ISSUE THREAD

**Issue by itachi-19** [dnl-blkv/mcdowell-cv#17]
I edited mcdowellcv.cls line 35 to this:
```Latex
 % Set font size and paper type
 \LoadClass[a4paper,\mainfontsize]{article}
```
Resulting in this:
![image](https://user-images.githubusercontent.com/16500619/134424696-dcd50485-66ab-4940-bde3-a86b12279d84.png)

**Comment by dnl-blkv** [comment]
Should be fixed. @goseind, please confirm :)

**Comment by martenmatrix** [comment]
@dnl-blkv The issue still persists for me. I believe this only happens with text in a `cvsubsection`.

**Comment by dnl-blkv** [comment]
@martenmatrix do you have an idea on how this can be fixed? It might be the PR missed the cvsubsection case :)

**Comment by martenmatrix** [comment]
@dnl-blkv I 've looked a bit more into it and I recognized that it only happens on `cvsubsection`'s where I have to explicitly pass a value to the `linesum` argument to stop it from overlapping with its content. This works when using the US letter format. In the A4 format, the argument does not prevent overlapping until I set it to `actual linesum + 1`.

**Comment by martenmatrix** [comment]
I think it's happening because the values of `\def\afterdoublelinesubsectionheaderspace` and `\def\aftermultilinesubsectionheaderspace` are not changed after setting the paper to A4, as far as I can read the code.
